<a href="https://colab.research.google.com/github/alexandre858/DataMinig/blob/main/Projet_suggestion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
#Partie 1 du programme 
#Annotation et classification
import os,sys
import json
import pathlib
import pandas
from PIL import Image
import matplotlib.pyplot as plot
import numpy
import math
from sklearn.cluster import MiniBatchKMeans

try:
   os.mkdir('data')
except:
    pass


donnees={}


 
path = '.'
 
files = os.listdir(path+"/images")

i=1
for name in files:
  if os.path.isfile("images/"+name):
    
    imgfile = Image.open("images/"+name)

    #algoritme qui détermine la couleur dominante d'une image
    #---------------------------------------------------
    numarray = numpy.array(imgfile.getdata(), numpy.uint8)
    if len(numarray.shape) ==2:

      cluster_count = 5

      clusters = MiniBatchKMeans(n_clusters = cluster_count)
      clusters.fit(numarray)

      npbins = numpy.arange(0, cluster_count + 1)
      histogram = numpy.histogram(clusters.labels_, bins=npbins)




      index_max=numpy.where(histogram[0]==max(histogram[0]))

      print(histogram[0],index_max)

      histogram[0][index_max]=0

      index_max=numpy.where(histogram[0]==max(histogram[0]))


      print(histogram[0],index_max)

      histogram[0][index_max]=0

      index_max_sec=numpy.where(histogram[0]==max(histogram[0]))

      print(histogram[0],index_max_sec)


      col_sec_r = math.ceil(clusters.cluster_centers_[index_max_sec[0][0]][0])
      col_sec_g = math.ceil(clusters.cluster_centers_[index_max_sec[0][0]][1])
      col_sec_b = math.ceil(clusters.cluster_centers_[index_max_sec[0][0]][2])

      col_dom_r=math.ceil(clusters.cluster_centers_[index_max[0][0]][0])
      col_dom_g=math.ceil(clusters.cluster_centers_[index_max[0][0]][1])
      col_dom_b=math.ceil(clusters.cluster_centers_[index_max[0][0]][2])
    else:
      col_dom_r="NaN"
      col_dom_g="NaN"
      col_dom_b="NaN"

      col_sec_r="NaN"
      col_sec_g="NaN"
      col_sec_b="NaN"

    #---------------------------------------------------




 
    #analyse taux de présence couleu
    #---------------------------------------------------
    histogram = imgfile.histogram()
    if (len(histogram)==1024 or len(histogram)==768):

      red = histogram[0:255]
      green = histogram[256:511]
      blue = histogram[512:767]

      total_red=0
      total_blue=0
      total_green=0

      j=0
      while j <255:
        total_red=total_red+red[j]*j
        total_blue=total_blue+blue[j]*j
        total_green=total_green+green[j]*j
        j+=1

    else:
      total_red="mono"
      total_green="mono"
      total_blue ="mono"
    #---------------------------------------------------


    #récupération des données sur le format de l'image
    #---------------------------------------------------
    hauteur=imgfile.size[0]
    largeur=imgfile.size[1]
    format=imgfile.format
    #---------------------------------------------------


    donnees[i-1]={"name":name,"size_high":hauteur,
                    "size_lenght":largeur,"format":format,
                      "red":total_red,"green":total_green,"blue":total_blue,
                        "col_dom_r":col_dom_r,"col_dom_g":col_dom_g,"col_dom_b":col_dom_b,
                            "col_sec_r":col_sec_r,"col_sec_g":col_sec_g,"col_sec_b":col_sec_b}

    i=i+1 

with open("data/data.json", "w") as file:
    json.dump(donnees, file,indent = 3)








[8983 2711 1800  239  667] (array([0]),)
[   0 2711 1800  239  667] (array([1]),)
[   0    0 1800  239  667] (array([2]),)
[12841   536   424   441   158] (array([0]),)
[  0 536 424 441 158] (array([1]),)
[  0   0 424 441 158] (array([3]),)
[  404 11511  1046  1105   334] (array([1]),)
[ 404    0 1046 1105  334] (array([3]),)
[ 404    0 1046    0  334] (array([2]),)
[  168 12821   223   410   778] (array([1]),)
[168   0 223 410 778] (array([4]),)
[168   0 223 410   0] (array([3]),)
[12056   638   658   855   193] (array([0]),)
[  0 638 658 855 193] (array([3]),)
[  0 638 658   0 193] (array([2]),)
[11593   759  1124   689   235] (array([0]),)
[   0  759 1124  689  235] (array([2]),)
[  0 759   0 689 235] (array([1]),)
[13115   382   148   532   223] (array([0]),)
[  0 382 148 532 223] (array([3]),)
[  0 382 148   0 223] (array([1]),)
[9891 2409  546  294 1260] (array([0]),)
[   0 2409  546  294 1260] (array([1]),)
[   0    0  546  294 1260] (array([4]),)
[12088   650   287   878   497]

In [ ]:
#test taux de presence
from PIL import Image
import matplotlib.pyplot as plot

path = '.'
 
files = os.listdir(path+"/images_test")

i=1
for name in files:
  if os.path.isfile("images_test/"+name):

imgfile = Image.open("./images/archeops.png")


histogram = imgfile.histogram()
# we have three bands (for this image)
red = histogram[0:255]
green = histogram[256:511]
blue = histogram[512:767]

total_red=0
total_blue=0
total_green=0

i=0
while i <255:
  total_red=total_red+red[i]*i
  total_blue=total_blue+blue[i]*i
  total_green=total_green+green[i]*i
  i+=1


print(total_red,total_blue,total_green)





 

334382 511705 574290


In [55]:
#test kmeans

from PIL import Image
import numpy
import math
import matplotlib.pyplot as plot
from sklearn.cluster import MiniBatchKMeans


path = '.'
 
files = os.listdir(path+"/images")

i=1
for name in files:
  if os.path.isfile("images/"+name):
    imgfile = Image.open("images/"+name)
    #numarray=numpy.zeros((imgfile.size[0]*imgfile.size[1],4))
    numarray = numpy.array(imgfile.getdata(), numpy.uint8)
    if len(numarray.shape) !=2:
      numarray = trackbug
      print("bugé",numarray)
    trackbug=numarray
    #cluster_count = x 
    
    #clusters = MiniBatchKMeans(n_clusters = cluster_count)
    #clusters.fit(numarray)
    
   # npbins = numpy.arange(0, cluster_count + 1)


######
    cluster_count = 4
    clusters = MiniBatchKMeans(n_clusters = cluster_count)

    clusters.fit(numarray)






    

    npbins = numpy.arange(0, cluster_count+1 )
    histogram = numpy.histogram(clusters.labels_, bins=npbins)


    index_max=numpy.where(histogram[0]==max(histogram[0]))

    print(histogram[0],index_max)

    histogram[0][index_max]=0

    index_max=numpy.where(histogram[0]==max(histogram[0]))


    print(histogram[0],index_max)

    histogram[0][index_max]=0

    index_max_sec=numpy.where(histogram[0]==max(histogram[0]))

    print(histogram[0],index_max_sec)


    print("couleur dominante rgb :" ,math.ceil(clusters.cluster_centers_[index_max[0][0]][0]),
            math.ceil(clusters.cluster_centers_[index_max[0][0]][1]) ,
              math.ceil(clusters.cluster_centers_[index_max[0][0]][2] ) )

    print("couleur secondaire rgb :" ,math.ceil(clusters.cluster_centers_[index_max_sec[0][0]][0]),
            math.ceil(clusters.cluster_centers_[index_max_sec[0][0]][1]) ,
              math.ceil(clusters.cluster_centers_[index_max_sec[0][0]][2] ) )




[3125 8983 2051  241] (array([1]),)
[3125    0 2051  241] (array([0]),)
[   0    0 2051  241] (array([2]),)
couleur dominante rgb : 244 247 249
couleur secondaire rgb : 110 148 142
[12841   589   970     0] (array([0]),)
[  0 589 970   0] (array([2]),)
[  0 589   0   0] (array([1]),)
couleur dominante rgb : 159 114 158
couleur secondaire rgb : 233 225 187
[11511  1423  1108   358] (array([0]),)
[   0 1423 1108  358] (array([1]),)
[   0    0 1108  358] (array([2]),)
couleur dominante rgb : 245 238 97
couleur secondaire rgb : 126 109 76
bugé [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[11511  1126  1419   344] (array([0]),)
[   0 1126 1419  344] (array([2]),)
[   0 1126    0  344] (array([1]),)
couleur dominante rgb : 245 237 93
couleur secondaire rgb : 129 112 77
[12821   454   955   170] (array([0]),)
[  0 454 955 170] (array([2]),)
[  0 454   0 170] (array([1]),)
couleur dominante rgb : 185 224 237
couleur secondaire rgb : 123 152 163
[12056   630  1522   1